/**
 * build.js — Vercel build script
 * Generates src/frontend/config.js from the BACKEND_URL environment variable.
 * Run by Vercel's buildCommand: "node build.js"
 */
const fs = require('fs');
const path = require('path');

const backendUrl = process.env.BACKEND_URL || 'http://localhost:8082';
const outputPath = path.join(__dirname, 'src', 'frontend', 'config.js');

const content = `// Auto-generated by build.js — do not edit manually.\nwindow.BACKEND_URL = '${backendUrl}';\n`;

fs.writeFileSync(outputPath, content, 'utf8');
console.log(`✓ config.js written → BACKEND_URL=${backendUrl}`);
