"""
MCP Feedback Agent
==================
Handles post-discovery feedback loops:
- Sends follow-up survey emails via Gmail MCP (or local simulation)
- Logs structured feedback to Google Docs MCP (or local files)

All operations fall back to saving locally in data/workspace/feedback/
when MCP servers are not available.
"""

import os
import sys
import json
import logging
from datetime import datetime

logger = logging.getLogger("feedback_agent")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
FEEDBACK_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "data", "workspace", "feedback")
)

SURVEY_TEMPLATE = """
Subject: How was your AI Music Discovery experience?

Hi {user_name},

Thank you for trying the Spotify AI Music Discovery Engine! We'd love your feedback
to help improve the experience.

Your Discovery Session Summary:
- Query: "{query}"
- Tracks Recommended: {track_count}
- Session Time: {session_time}

Please take a moment to answer these questions:

1. How relevant were the recommended tracks to your request? (1-5)
   [ ] 1 — Not relevant at all
   [ ] 2 — Slightly relevant
   [ ] 3 — Moderately relevant
   [ ] 4 — Very relevant
   [ ] 5 — Perfectly matched

2. Did you discover any new artists or songs you hadn't heard before?
   [ ] Yes, several
   [ ] Yes, one or two
   [ ] No, all were familiar

3. How likely are you to use this feature again? (1-5)
   [ ] 1 — Very unlikely
   [ ] 2 — Unlikely
   [ ] 3 — Neutral
   [ ] 4 — Likely
   [ ] 5 — Very likely

4. What would make the discovery experience better?
   [Open text response]

5. Any tracks you particularly loved or disliked?
   [Open text response]

Thank you for your feedback!
— Spotify Growth Team

This email was generated by the AI Discovery Feedback Agent.
Recipient: stakeholders@spotify.com
"""

FEEDBACK_DOC_HEADER = """# Aggregated User Feedback Log
## Spotify AI Music Discovery Engine

_Last updated: {timestamp}_

---

"""

FEEDBACK_ENTRY_TEMPLATE = """
### Feedback #{entry_id} — {timestamp}
- **User**: {user_email}
- **Query**: "{query}"
- **Tracks Shown**: {track_count}
- **Relevance Score**: {relevance}/5
- **Discovery Success**: {discovery}
- **Reuse Likelihood**: {reuse}/5
- **Improvement Suggestion**: {improvement}
- **Track Feedback**: {track_feedback}

---
"""


# ---------------------------------------------------------------------------
# MCP Integration Check
# ---------------------------------------------------------------------------
def _check_mcp():
    """Check if MCP client libraries are available."""
    try:
        from mcp import ClientSession, StdioServerParameters
        from mcp.client.stdio import stdio_client
        return True
    except ImportError:
        return False


# ---------------------------------------------------------------------------
# Survey Email
# ---------------------------------------------------------------------------
def send_feedback_survey(
    user_email: str,
    session_summary: dict,
    gmail_mcp_server: str = "",
) -> dict:
    """
    Send a personalized follow-up questionnaire to a user.

    Args:
        user_email: Recipient email address.
        session_summary: Dict with query, track_count, session_time.
        gmail_mcp_server: Path to Gmail MCP server (optional).

    Returns:
        Status dict with mode and file path (if simulated).
    """
    user_name = user_email.split("@")[0].replace(".", " ").title()

    email_body = SURVEY_TEMPLATE.format(
        user_name=user_name,
        query=session_summary.get("query", "N/A"),
        track_count=session_summary.get("track_count", 0),
        session_time=session_summary.get("session_time", "N/A"),
    )

    # Try MCP first
    if gmail_mcp_server and _check_mcp():
        try:
            import asyncio
            from mcp import ClientSession, StdioServerParameters
            from mcp.client.stdio import stdio_client

            async def _send():
                server_params = StdioServerParameters(command="node", args=[gmail_mcp_server])
                async with stdio_client(server_params) as (read_stream, write_stream):
                    async with ClientSession(read_stream, write_stream) as session:
                        await session.initialize()
                        await session.call_tool("send_email", {
                            "to": user_email,
                            "subject": "How was your AI Music Discovery experience?",
                            "body": email_body,
                        })
                        return True

            asyncio.run(_send())
            logger.info("Survey email sent via Gmail MCP to %s", user_email)
            return {"status": "success", "mode": "mcp", "recipient": user_email}
        except Exception as exc:
            logger.warning("Gmail MCP failed: %s — falling back to simulation", exc)

    # Local simulation fallback
    os.makedirs(FEEDBACK_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"survey_email_{timestamp}_{user_email.split('@')[0]}.txt"
    filepath = os.path.join(FEEDBACK_DIR, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"TO: {user_email}\n")
        f.write(f"FROM: growth-team@spotify.com\n")
        f.write(f"DATE: {datetime.now().isoformat()}\n")
        f.write(f"{'='*60}\n")
        f.write(email_body)

    logger.info("Survey email simulated and saved to %s", filepath)
    return {
        "status": "success",
        "mode": "simulation",
        "recipient": user_email,
        "file": filepath,
    }


# ---------------------------------------------------------------------------
# Feedback Logging
# ---------------------------------------------------------------------------
def log_feedback_to_docs(
    feedback_data: dict,
    docs_mcp_server: str = "",
) -> dict:
    """
    Append structured feedback to the aggregate feedback document.

    Args:
        feedback_data: Dict containing user_email, query, relevance, etc.
        docs_mcp_server: Path to Google Docs MCP server (optional).

    Returns:
        Status dict with mode and file path.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    entry = FEEDBACK_ENTRY_TEMPLATE.format(
        entry_id=feedback_data.get("entry_id", int(datetime.now().timestamp()) % 10000),
        timestamp=timestamp,
        user_email=feedback_data.get("user_email", "anonymous@user.com"),
        query=feedback_data.get("query", "N/A"),
        track_count=feedback_data.get("track_count", 0),
        relevance=feedback_data.get("relevance", "N/A"),
        discovery=feedback_data.get("discovery", "N/A"),
        reuse=feedback_data.get("reuse", "N/A"),
        improvement=feedback_data.get("improvement", "No suggestion provided"),
        track_feedback=feedback_data.get("track_feedback", "No specific feedback"),
    )

    # Try MCP first
    if docs_mcp_server and _check_mcp():
        try:
            import asyncio
            from mcp import ClientSession, StdioServerParameters
            from mcp.client.stdio import stdio_client

            async def _append():
                server_params = StdioServerParameters(command="node", args=[docs_mcp_server])
                async with stdio_client(server_params) as (read_stream, write_stream):
                    async with ClientSession(read_stream, write_stream) as session:
                        await session.initialize()
                        await session.call_tool("append_text", {
                            "content": entry,
                        })
                        return True

            asyncio.run(_append())
            logger.info("Feedback logged via Google Docs MCP")
            return {"status": "success", "mode": "mcp"}
        except Exception as exc:
            logger.warning("Google Docs MCP failed: %s — falling back to simulation", exc)

    # Local simulation fallback
    os.makedirs(FEEDBACK_DIR, exist_ok=True)
    feedback_log = os.path.join(FEEDBACK_DIR, "aggregated_feedback_log.md")

    # Create header if file doesn't exist
    if not os.path.exists(feedback_log):
        with open(feedback_log, "w", encoding="utf-8") as f:
            f.write(FEEDBACK_DOC_HEADER.format(timestamp=timestamp))

    # Append the entry
    with open(feedback_log, "a", encoding="utf-8") as f:
        f.write(entry)

    # Also save as individual JSON for programmatic access
    json_file = os.path.join(FEEDBACK_DIR, "feedback_entries.jsonl")
    with open(json_file, "a", encoding="utf-8") as f:
        feedback_data["timestamp"] = timestamp
        f.write(json.dumps(feedback_data, ensure_ascii=False) + "\n")

    logger.info("Feedback logged locally to %s", feedback_log)
    return {
        "status": "success",
        "mode": "simulation",
        "log_file": feedback_log,
        "json_file": json_file,
    }


def get_feedback_stats() -> dict:
    """
    Read the feedback log and compute summary statistics.

    Returns:
        Dict with total_entries, avg_relevance, avg_reuse, discovery_rate.
    """
    json_file = os.path.join(FEEDBACK_DIR, "feedback_entries.jsonl")
    if not os.path.exists(json_file):
        return {"total_entries": 0, "message": "No feedback data collected yet."}

    entries = []
    with open(json_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except json.JSONDecodeError:
                    continue

    if not entries:
        return {"total_entries": 0}

    relevance_scores = [e.get("relevance", 0) for e in entries if isinstance(e.get("relevance"), (int, float))]
    reuse_scores = [e.get("reuse", 0) for e in entries if isinstance(e.get("reuse"), (int, float))]
    discovery_yes = sum(1 for e in entries if "yes" in str(e.get("discovery", "")).lower())

    return {
        "total_entries": len(entries),
        "avg_relevance": round(sum(relevance_scores) / len(relevance_scores), 2) if relevance_scores else 0,
        "avg_reuse_likelihood": round(sum(reuse_scores) / len(reuse_scores), 2) if reuse_scores else 0,
        "discovery_rate": round(discovery_yes / len(entries) * 100, 1) if entries else 0,
    }
